import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Provider from "@/providers";

import './globals.css'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.variable}>
      <Provider>
        {children}
      </Provider>
      </body>
    </html>
  )
}
