import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import NavBar from "@/components/layout/NavBar";

import ThemeProvider from "@/providers/ThemeProvider";

import "../globals.scss";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type LayoutProps = {
  params: { locale: string };
  children: React.ReactNode;
};

export default function RootLayout({ params, children }: LayoutProps) {
  const { locale } = params;

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={inter.variable}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <NavBar params={params} />

          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
