import React from "react";
import { clsx } from "clsx";
// import { MagicMotion } from "react-magic-motion";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import NavBar from "@/components/layout/NavBar";

import { i18n } from "@/dictionaries/i18n-config";
import ThemeProvider from "@/providers/ThemeProvider";

import "./globals.scss";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: string };
}) {
  return (
    <html lang={params.lang} suppressHydrationWarning>
      <body className={clsx(inter.variable, "transition duration-300")}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <NavBar lang={params.lang} />

          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}

export default RootLayout;
